/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package markdowntohtml;

/**
 * Markdown to HTML convert application. This class uses a parser to look for Markdown tags.
 * The parser will then replace the tags with html tags.
 *
 */
public class MarkdownToHTML {
    public static void main(String[] args) {
        String markdown = "# Header one\n" +
                "\n" +
                "Hello there\n" +
                "\n" +
                "How are you?  \n" +
                "What's going on?\n" +
                "\n" +
                "## Another Header\n" +
                "\n" +
                "This is a paragraph [with an inline link](http://google.com). Neat, eh?\n" +
                "\n" +
                "## This is a header [with a link](http://yahoo.com)\n";
//        String markdown = "# Sample Document\n" +
//                "\n" +
//                "Hello!\n" +
//                "\n" +
//                "This is sample markdown for the [Mailchimp](https://www.mailchimp.com) homework assignment.";
        try {
            System.out.println(new Parser().parse(markdown));
        } catch (Exception e) {
            System.out.println("Exception: " + e.getMessage());
        }
    }
}
